In [1]:
#ques 1-->
import random

rows = 20000
cols = 10000

with open("large_matrix.txt", "w") as f:
    for i in range(rows):
        row = [str(random.randint(0, 100)) for _ in range(cols)]
        f.write(",".join(row) + "\n")

print("Data file created successfully.")

Data file created successfully.


In [2]:
#ques 2-->
import numpy as np

matrix = np.random.randint(1, 10, (5, 5))

first_row = matrix[0]

for i in range(1, len(matrix)):
    matrix[i] = first_row + i   # assigning based on first row

print(matrix)

[[ 1  8  8  2  9]
 [ 2  9  9  3 10]
 [ 3 10 10  4 11]
 [ 4 11 11  5 12]
 [ 5 12 12  6 13]]


In [3]:
#ques 3-->
import numpy as np
from collections import defaultdict

matrix = np.random.randint(1, 6, (4, 4))

groups = defaultdict(list)

for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        groups[matrix[i][j]].append((i, j))

print("Matrix:\n", matrix)
print("\nGrouped Elements:")
for key, value in groups.items():
    print(key, "->", value)

Matrix:
 [[4 5 1 4]
 [1 1 4 4]
 [1 4 3 4]
 [2 2 4 5]]

Grouped Elements:
4 -> [(0, 0), (0, 3), (1, 2), (1, 3), (2, 1), (2, 3), (3, 2)]
5 -> [(0, 1), (3, 3)]
1 -> [(0, 2), (1, 0), (1, 1), (2, 0)]
3 -> [(2, 2)]
2 -> [(3, 0), (3, 1)]


In [4]:
#ques 4-->
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

addition = A + B
subtraction = A - B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)

Matrix A:
 [[3 4 2]
 [1 9 4]
 [9 3 9]]
Matrix B:
 [[8 8 7]
 [4 5 7]
 [9 5 9]]
Addition:
 [[11 12  9]
 [ 5 14 11]
 [18  8 18]]
Subtraction:
 [[-5 -4 -5]
 [-3  4 -3]
 [ 0 -2  0]]


In [5]:
#ques 5-->
import numpy as np

n = 4

matrix = np.random.choice(range(0, 100, 2), (n, n))  # only even numbers

print("Matrix:\n", matrix)

Matrix:
 [[62 16 16 78]
 [ 4 12 98 80]
 [20 36 68  6]
 [32 26 58 80]]


In [6]:
#ques 6-->
# Tuple matrix
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

row_sums = []

for row in matrix:
    row_sums.append(sum(row))

print("Row-wise sums:", row_sums)

Row-wise sums: [6, 15, 24]
